# Generated by Django 2.2.8 on 2020-03-01 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutionrequest',
            name='tution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.Tution'),
        ),
        migrations.AddField(
            model_name='tution',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tution.Category'),
        ),
        migrations.AddField(
            model_name='tution',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tution_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tution_child', to='tution.Category'),
        ),
        migrations.AddField(
            model_name='categoryrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tution_parent', to='tution.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='tutionrequest',
            unique_together={('tution', 'student')},
        ),
    ]
