# Generated by Django 2.2.8 on 2020-02-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag_type',
            field=models.IntegerField(choices=[(1, 'Subject'), (3, 'Course'), (2, 'Subject Category'), (4, 'Grade'), (5, 'Group')]),
        ),
    ]
