# Generated by Django 2.2.8 on 2020-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0002_auto_20200301_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='tution',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
