# Generated by Django 2.2.8 on 2020-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0003_auto_20200127_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrelation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
