# Generated by Django 2.2.8 on 2020-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_categoryrelation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
