# Generated by Django 2.2.8 on 2020-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_auto_20200205_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag_type',
            field=models.IntegerField(choices=[(1, 'Tag'), (2, 'Group'), (3, 'Search Tag')]),
        ),
    ]
