# Generated by Django 2.2.8 on 2020-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0006_auto_20200208_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrelation',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoryrelation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
