# Generated by Django 2.2.8 on 2020-02-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tution', '0009_tutionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutionrequest',
            name='for_user',
        ),
        migrations.RemoveField(
            model_name='tutionrequest',
            name='from_user',
        ),
        migrations.AddField(
            model_name='tutionrequest',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tution_request_user1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutionrequest',
            name='user2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tution_request_user2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
