# Generated by Django 2.2.8 on 2020-02-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0010_auto_20200212_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutionrequest',
            old_name='user2',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='tutionrequest',
            old_name='user1',
            new_name='tutor',
        ),
    ]
