# Generated by Django 2.2.8 on 2020-02-16 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tution', '0011_auto_20200212_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('area', models.CharField(max_length=255)),
                ('timing', models.PositiveSmallIntegerField(choices=[(1, 'Any Time'), (2, 'Morning'), (3, 'Afternoon'), (4, 'Evening')])),
                ('location', models.PositiveSmallIntegerField(choices=[(1, 'At Tutor Home'), (2, 'At Student Home'), (3, 'At Insitute')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tution.Category')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tution_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
