# Generated by Django 2.2.8 on 2020-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0013_tution_batch_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tution',
            name='area',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TutionRequest',
        ),
    ]
