# Generated by Django 2.2.8 on 2020-02-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0014_auto_20200223_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='tag_type',
            field=models.IntegerField(choices=[(1, 'Tag'), (2, 'Group'), (3, 'Search Tag')], db_index=True),
        ),
    ]
