# Generated by Django 2.2.8 on 2020-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0016_tutionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutionrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutionrequest',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
