# Generated by Django 2.2.8 on 2020-02-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0017_auto_20200225_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutionrequest',
            old_name='mobile',
            new_name='phone',
        ),
    ]
