# Generated by Django 2.2.8 on 2020-02-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0018_auto_20200226_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutionrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
