# Generated by Django 2.2.8 on 2020-02-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0019_auto_20200226_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tution',
            name='batch_size',
            field=models.IntegerField(default=1),
        ),
    ]
