# Generated by Django 2.2.8 on 2020-02-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timing',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Any Time'), (2, 'Morning'), (3, 'Afternoon'), (4, 'Evening')], null=True),
        ),
    ]
