# Generated by Django 2.2.8 on 2020-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_preference',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'At Tutor Home'), (2, 'At Student Home'), (3, 'At Insitute')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='price_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timing',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Any Time'), (2, 'Morning'), (3, 'Afternoon'), (4, 'Evening')], null=True),
        ),
    ]
