# Generated by Django 2.2.8 on 2020-02-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200205_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
