# Generated by Django 2.2.8 on 2020-02-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_usercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location_preference',
        ),
    ]
