# Generated by Django 2.2.8 on 2020-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usercategory_userlocationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
