# Generated by Django 2.2.8 on 2020-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200216_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocationpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlocationpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='po_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allzipcode',
            name='zipcode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserLocationPreference',
        ),
    ]
